const DATA={
  '2x1':{image:'/assets/pdf-2x1.jpg',title:'2×1 · 轻量服务',text:'标题、主副信息、焦点数字与右侧动作等 4 种范式；适合最多 3 个紧凑信息单元。',caption:'PDF 第 1 页：第一行抽象为 2×1 模板，下面实例用于验证替换能力。',frames:[['9/12 主信息','3/12 动作'],['9/12 主副信息','3/12 图标'],['8/12 指标','4/12 状态']]},
  '2x2':{image:'/assets/pdf-2x2.jpg',title:'2×2 · 标准服务',text:'正文、大图、列表、环形进度、底部动作、四宫格等 9 种范式；模板允许同体量组件互换。',caption:'PDF 第 2 页：第一行范式覆盖主要 2×2 服务卡片，后续实例构成测试语料。',frames:[['标题','正文 12/12'],['指标 7/12','状态 5/12','底部动作'],['操作','操作','操作','操作']]},
  '3x2':{image:'/assets/pdf-3x2.jpg',title:'3×2 · 横向服务',text:'服务操作带、搜索快捷入口、内容操作、媒体控制、横向图表、列表和图文叙事等 7 种范式。',caption:'PDF 第 3 页：第一行正式抽象为 3×2 横向模板，下面实例用于回归验证。',frames:[['标题 8/12','动作 4/12','四项快捷入口'],['媒体 3/12','标题 6/12','控制 3/12','操作带'],['指标','辅助信息','横向图表']]},
  '3x3':{image:'/assets/pdf-3x3.jpg',title:'3×3 · 完整信息',text:'将 PDF 大方卡范式适配为编辑正文、媒体列表、图表焦点、长列表和综合仪表盘 5 类。',caption:'PDF 第 4 页：大方卡第一行及天气/日历实例，是 3×3 模板的设计基础。',frames:[['标题 12/12','大留白','正文'],['媒体 5/12','标题 7/12','列表 12/12'],['主指标','状态','详情','详情','详情']]}
};
function draw(size){const d=DATA[size],root=document.getElementById('wireframes');document.getElementById('pdfRef').src=d.image;document.getElementById('pdfCaption').textContent=d.caption;document.getElementById('sizeTitle').textContent=d.title;document.getElementById('sizeText').textContent=d.text;root.replaceChildren();for(const [i,parts] of d.frames.entries()){const card=document.createElement('div');card.className='mini-card';for(const part of parts){const slot=document.createElement('span');slot.textContent=part;card.append(slot)}const label=document.createElement('b');label.textContent='范式 '+String(i+1).padStart(2,'0');card.append(label);root.append(card)}}
document.querySelectorAll('[data-size]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-size]').forEach(x=>x.classList.remove('active'));button.classList.add('active');draw(button.dataset.size)});draw('2x1');
const templateSection=document.querySelector('.template-study')?.closest('.doc-section');if(templateSection){const section=document.createElement('section');section.className='doc-section';section.innerHTML='<small>LAYOUT DECISION MAP</small><h2>布局引擎如何做决定</h2><div class="decision-map"><article><b>① SIZE GATE</b><span>按卡片尺寸筛模板</span></article><i>→</i><article><b>② SCORE</b><span>type + family + footprint<br>role + priority</span></article><i>→</i><article><b>③ ASSIGN</b><span>全局最高分槽位组合</span></article><div class="decision-split"><span>覆盖充分</span><span>仍有语素</span><span>覆盖过低</span></div><div class="decision-results"><article><b>TEMPLATE</b><span>标准模板输出</span></article><article><b>WHITESPACE</b><span>扫描空闲网格补位</span></article><article><b>FREE</b><span>自由网格兜底</span></article></div><div class="decision-merge">↓</div><article class="render-node"><b>RenderSpec v0.2</b><span>DSL · A2UI v0.9 · HTML/CSS</span></article></div>';templateSection.after(section)}
