const rawCases={
1:[['搜索','TEXT ICON'],['未接来电','TEXT STATUS BUTTON'],['步数','METRIC ICON'],['北京天气','STATUS METRIC ICON'],['联系人快捷拨号','TEXT BUTTON'],['24小时内未接来电','TEXT STATUS ICON'],['睡眠时长','TEXT METRIC PROGRESS'],['短视频剪辑','TEXT BUTTON'],['睡前 BGM','TEXT STATUS BUTTON'],['舒缓减压呼吸','TEXT PROGRESS BUTTON'],['饮食日记','TEXT BUTTON'],['电影继续播放','TEXT STATUS BUTTON'],['开始运动','TEXT BUTTON'],['闹钟提醒','TEXT STATUS BUTTON']],
2:[['歌单推荐','TEXT IMAGE BUTTON'],['地球资讯','IMAGE TEXT'],['宇宙探险记','TEXT IMAGE BUTTON'],['附近加油站','TEXT STATUS BUTTON'],['手机使用','METRIC LIST PROGRESS'],['安装状态扫描','PROGRESS STATUS BUTTON'],['今日步数','METRIC BUTTON'],['今日无日程','TEXT METRIC'],['常用联系人','TEXT BUTTON BUTTON BUTTON BUTTON'],['今日会议','TEXT LIST'],['运动摄影','IMAGE TEXT BUTTON'],['科技新闻','IMAGE TEXT'],['CityPop Music','TEXT IMAGE BUTTON'],['应用检测','TEXT BUTTON'],['还可摄入','METRIC LIST PROGRESS'],['春节倒计时','METRIC TEXT'],['睡眠评分','METRIC STATUS BUTTON'],['北京天气方卡','STATUS METRIC TEXT'],['相机快捷方式','BUTTON BUTTON BUTTON BUTTON'],['全部待办','TEXT LIST'],['录音机','TEXT PROGRESS BUTTON'],['插画设计指南','TEXT IMAGE'],['阳台环境','TEXT METRIC METRIC METRIC'],['压力检测','METRIC STATUS BUTTON'],['每日技巧','TEXT LIST'],['Sound X','TEXT IMAGE BUTTON'],['会议提醒','STATUS TEXT BUTTON'],['跑步课程','TEXT IMAGE PROGRESS']],
3:[['车主服务','TEXT BUTTON BUTTON BUTTON BUTTON'],['应用搜索','TEXT BUTTON BUTTON BUTTON BUTTON'],['英雄联盟','TEXT IMAGE BUTTON BUTTON'],['粉雾海音乐','TEXT IMAGE BUTTON BUTTON BUTTON'],['横向天气','STATUS METRIC LIST'],['备忘录','TEXT LIST'],['网站推荐','IMAGE TEXT BUTTON'],['全屋设备','TEXT BUTTON BUTTON BUTTON BUTTON'],['发现更多应用','TEXT BUTTON BUTTON BUTTON'],['月历','METRIC LIST'],['会议日程','TEXT LIST BUTTON'],['每日精选','TEXT LIST IMAGE'],['维多利亚影视','IMAGE TEXT BUTTON'],['古典音乐','IMAGE TEXT BUTTON BUTTON BUTTON'],['汽车资讯','IMAGE TEXT LIST']],
4:[['Cybertruck 资讯','IMAGE TEXT'],['古典播放列表','IMAGE TEXT LIST BUTTON'],['月历大卡','METRIC LIST'],['备忘录大卡','TEXT LIST'],['视频通话','IMAGE BUTTON BUTTON BUTTON'],['媒体推荐列表','IMAGE TEXT LIST BUTTON'],['十日天气','STATUS METRIC LIST PROGRESS'],['两日日程','TEXT LIST'],['时尚图集','IMAGE TEXT LIST'],['汽车新闻流','IMAGE TEXT LIST'],['书籍推荐','TEXT IMAGE LIST']]
};
const sizeByPage={1:'2x1',2:'2x2',3:'3x2',4:'3x3'},cases=[];
for(const [page,items] of Object.entries(rawCases))for(const [index,[title,types]] of items.entries()){const morphemes=types.split(' ').map((type,i)=>({type,role:i===0?'PRIMARY':['BUTTON','SWITCH','SLIDER'].includes(type)?'PRIMARY_ACTION':'SECONDARY',priority:Math.max(35,90-i*8),label:type}));const prompt=`生成一张${title}服务卡片，按照${sizeByPage[page].replace('x','×')}尺寸组织信息，重点突出${title}的核心内容，并提供必要的状态、数据或操作。`;cases.push({id:`P${page}-${String(index+1).padStart(2,'0')}`,page:Number(page),source:`PDF P${page} 实例 ${index+1}`,size:sizeByPage[page],title,prompt,morphemes})}
const token=document.querySelector('meta[name=request-token]').content,grid=document.getElementById('caseGrid'),results=new Map();
async function runCase(test){const response=await fetch('/api/layout-test',{method:'POST',headers:{'Content-Type':'application/json','X-Workbench-Token':token},body:JSON.stringify(test)});if(!response.ok)throw Error('HTTP '+response.status);const data=await response.json(),layout=data.layout;return {...data,template:layout.templateName,mode:layout.mode,confidence:layout.confidence,unplaced:layout.unplaced.length}}
function visible(){const page=document.getElementById('caseFilter').value;return cases.filter(x=>page==='all'||String(x.page)===page)}
function summary(){let pass=0,fallback=0,unplaced=0;for(const result of results.values()){if(!result.error&&!result.unplaced)pass++;if(result.mode==='FREE')fallback++;if(result.unplaced)unplaced++}document.getElementById('passed').textContent=pass;document.getElementById('fallback').textContent=fallback;document.getElementById('unplaced').textContent=unplaced;document.getElementById('pending').textContent=visible().filter(x=>!results.has(x.id)).length}
function renderCases(){grid.replaceChildren();for(const test of visible()){const card=document.createElement('article');card.className='case-card';card.innerHTML=`<header><b>${test.id}</b><small>${test.size.replace('x','×')}</small></header><h3>${test.title}</h3><p>${test.source}</p><p class="case-prompt">${test.prompt}</p><div class="types">${test.morphemes.map(x=>`<i>${x.type}</i>`).join('')}</div><footer><button type="button">检查输入 / 布局 / 代码</button><output>待运行</output></footer>`;const button=card.querySelector('button'),output=card.querySelector('output');const cached=results.get(test.id);if(cached)show(card,output,cached);button.onclick=async()=>{button.disabled=true;output.textContent='运行中…';try{let result=results.get(test.id);if(!result||result.error){result=await runCase(test);results.set(test.id,result)}show(card,output,result);inspect(test,result)}catch(error){const result={error:error.message};results.set(test.id,result);show(card,output,result)}finally{button.disabled=false;summary()}};grid.append(card)}summary()}
function show(card,output,result){card.classList.remove('pass','warn','fail');if(result.error){card.classList.add('fail');output.textContent=result.error}else{card.classList.add(result.unplaced?'fail':result.mode==='FREE'?'warn':'pass');output.textContent=`${result.template} · ${Math.round(result.confidence*100)}%${result.unplaced?' · 裁剪 '+result.unplaced:''}`}}
function previewComponent(item){const box=document.createElement('div');box.className='ui-item ui-'+item.type.toLowerCase();const label=document.createElement('span');label.className='ui-label';label.textContent=item.label;const value=document.createElement(item.type==='BUTTON'?'button':item.type==='LIST'?'ul':'strong');if(item.type==='BUTTON')value.textContent='执行';else if(item.type==='SWITCH'){value.className='ui-switch on';value.append(document.createElement('i'))}else if(item.type==='LIST'){for(let i=0;i<3;i++){const li=document.createElement('li');li.textContent='列表内容 '+(i+1);value.append(li)}}else if(item.type==='IMAGE'||item.type==='ICON'){value.textContent='IMAGE';value.className='media-placeholder'}else value.textContent=item.type==='METRIC'?'99':item.type==='PROGRESS'?'68%':'示例内容';box.append(label,value);return box}
function renderCasePreview(spec){const root=document.getElementById('casePreview');root.replaceChildren();const card=document.createElement('article'),tokens=spec.style.tokens;card.className='ui-card';card.dataset.size=spec.surface.size;card.style.setProperty('--card-bg',tokens.cardBg);card.style.setProperty('--card-fg',tokens.cardFg);card.style.setProperty('--accent',tokens.accent);card.style.setProperty('--muted',tokens.muted);card.style.setProperty('--radius',tokens.radius+'px');const title=document.createElement('h2');title.textContent=spec.title;const layout=document.createElement('div');layout.className='layout-grid';layout.style.gridTemplateRows=`repeat(${spec.grid.rows},1fr)`;for(const slot of spec.slots){const section=document.createElement('section'),r=slot.rect;section.style.gridColumn=`${r.x+1}/span ${r.w}`;section.style.gridRow=`${r.y+1}/span ${r.h}`;if(slot.component)section.append(previewComponent(slot.component));else{const p=document.createElement('div');p.className='media-placeholder';p.textContent=(slot.placeholder||'IMAGE')+' PLACEHOLDER';section.append(p)}layout.append(section)}card.append(title,layout);root.append(card)}
let inspected=null,inspectTab='prompt';function inspect(test,result){inspected={test,result};document.getElementById('caseInspector').hidden=false;document.getElementById('inspectSource').textContent=test.source+' · '+test.id;document.getElementById('inspectTitle').textContent=test.title;document.getElementById('inspectMeta').textContent=`${test.size.replace('x','×')} · ${result.template} · ${result.mode} · 覆盖率 ${Math.round(result.confidence*100)}%`;renderCasePreview(result.renderSpec);showInspectTab();document.getElementById('caseInspector').scrollIntoView({behavior:'smooth',block:'start'})}
function showInspectTab(){if(!inspected)return;const {test,result}=inspected;let content;if(inspectTab==='prompt')content=test.prompt;else if(inspectTab==='morpheme')content=result.morphemeSpec;else if(inspectTab==='layout')content=result.layout;else if(inspectTab==='a2ui')content=result.outputs.a2ui;else content=`<!-- card.html -->\n${result.outputs.html_css.files['card.html']}\n\n/* card.css */\n${result.outputs.html_css.files['card.css']}\n\n/* CSS variables */\n${JSON.stringify(result.outputs.html_css.variables,null,2)}`;document.getElementById('inspectCode').textContent=typeof content==='string'?content:JSON.stringify(content,null,2)}
const showProtocolTab=showInspectTab;showInspectTab=function(){if(!inspected)return;const {test,result}=inspected;if(inspectTab==='dsl')document.getElementById('inspectCode').textContent=result.outputs.dsl.code;else if(inspectTab==='a2ui')document.getElementById('inspectCode').textContent=result.outputs.a2ui.ndjson;else showProtocolTab()};document.querySelectorAll('[data-inspect]').forEach(button=>button.onclick=()=>{inspectTab=button.dataset.inspect;document.querySelectorAll('[data-inspect]').forEach(x=>x.classList.toggle('active',x===button));showInspectTab()});document.getElementById('closeInspector').onclick=()=>document.getElementById('caseInspector').hidden=true;
document.getElementById('sendWorkbench').onclick=()=>{if(!inspected)return;localStorage.setItem('genui_pdf_case',JSON.stringify({prompt:inspected.test.prompt,size:inspected.test.size}));location.href='/'};
document.getElementById('caseFilter').onchange=renderCases;document.getElementById('runAll').onclick=async event=>{const button=event.currentTarget;button.disabled=true;for(const test of visible()){if(results.has(test.id))continue;try{results.set(test.id,await runCase(test))}catch(error){results.set(test.id,{error:error.message})}renderCases()}button.disabled=false};document.getElementById('caseCount').textContent=cases.length;renderCases();
